apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-muflih-certificate
  namespace: default  # Or the relevant namespace
spec:
  secretName: api-muflih-tls-secret  # The name of the secret to store the certificate
  issuerRef:
    name: letsencrypt-prod  # The name of the ClusterIssuer or Issuer you created earlier
    kind: ClusterIssuer
  dnsNames:
    - api.muflih.online
